### ISSUE TITLE
ApplyRawDamage needs changed.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#125]
ApplyRawDamage should not be limited to the range 0..255. Some "bosses" might have HP in the tens of thousands on some servers and if there is a special "boss weapon" that can deal damage greater than 255 it fails to do any damage because ApplyRawDamage will not accept a number above 255.

**Comment by KevinEady** [comment]
https://github.com/polserver/polserver/blob/12d6186d10422c3ad4313ca9ac0ca3cb3da47105/pol-core/pol/module/vitalmod.cpp#L64

It looks like the range is `[0, 30000]` inclusive? Where do you see `255` being the limit?

Do you get an error passing in `255`? Can you post the error if you do?

**Comment by Daviex** [comment]
@KevinEady 
As I can see over the docs, it seems that the function ApplyRawDamage accept a value that goes between a 0 value to 255 as he say. I think the limit is into the function ApplyRawDamage and not where the damage is actually executed.

Ref: [http://docs.polserver.com/pol100/fullfunc.php?xmlfile=vitalsem#ApplyRawDamage](ApplyRawDamage)

**Comment by KevinEady** [comment]
Ohhh I was looking at `ApplyDamage` not `ApplyRawDamage`, ooops i see

**Comment by frozenblit** [comment]
There are two issues here:
1) The doc is wrong. The range is up to 65535 (USHRT_MAX).
2) POL expects an int parameter (as the doc says) but Yukiko was calling ApplyRawDamage() with a double:
```js
 var trgt := Target(who);
 Print("Life = " + CStr(AP_GetVital(trgt, VITALID_LIFE)));
 Print("Life + 51 = " + CStr(AP_GetVital(trgt, VITALID_LIFE) + 51));
 Print("ApplyRawDamage print = " + ApplyRawDamage(trgt, AP_GetVital(trgt, VITALID_LIFE) + 51));
 return;
```

Because ApplyDamage() can cope with doubles, I can see how one could expect ApplyRawDamage() to do the same. We should consider whether we want to round or truncate it (or even just return a better error). I'd be inclined to round up.
