### ISSUE TITLE
Migrate pol 097 to 099

### ISSUE THREAD

**Issue by vtajzich** [polserver/polserver#14]
Hi,

we want to migrate our polserver from 097 to latest master (099). 

Is there any migration guide what needs to be changed, updated? 
Changelog with deprecated / removed stuff?

Thanks

**Comment by gtozzi** [comment]
Hi @vtajzich!

There is no direct migration guide from POL097 to POL099.
Is is not doable: because every script basis is affected differently by the changes.

Anyway, there is a complete and very detailed changelog. You can find it here: https://docs.polserver.com/pol099/corechanges.php

You can reads the changes and see how they affect your script base, then modify it accordingly when needed. It could seem a long process, but I've already done it myself and it didn't take more than a couple of days. As a bonus, while reading the changelog you'll get aware of new features and inspired for introducing new features in your script base too... or at least that's what's been for me.

Have a good job ;)
