### ISSUE TITLE
I am getting a strange run time error.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/polserver#439]
I have been integrating the mounts package into the Distro but I am getting this error in the console when I double-click my mounted character:
`WARNING: scripts/misc/dblclickself.ecl: Unable to find module npc`
The script compiles with no errors. My modules are in the correct directory `/scripts/modules`. Just to be "safe" I ensured there was only one `use npc` statement in the code chain. I know that shouldn't matter but...
I haven't committed the scripts that I have been working on yet.
If I understand correctly, this error should not happen if eCompile can find the module during compile time.

**Comment by KevinEady** [comment]
This happens because `dblclickself` is not an NPC script. Only NPC scripts have the `npc` module available at _runtime_. 

The script compiles fine because the module is there at _compilation_ time, but not available at _runtime_. This type of error also comes when eg. you try to `runecl` a script that uses the `sql` module.
