### ISSUE TITLE
Malaligned if statement based on polcore docs.

### ISSUE THREAD

**Issue by sigmantium** [polserver/polserver#50]
https://github.com/polserver/polserver/blob/dbb25bdb62700a1827dc5d779f62a8919adbb38a/pol-core/pol/dblclick.cpp#L93

according to the docs the dblclickself script should run before this line so that its up to the developer if they want to enable sending the paperdoll rather than the core deciding for them. Based on the docs if you have a print in the dblclickself.src to simply print "test" then it applies when the player is mounted but not when the player is unmounted. Thus making common dblclickself that start with
`var mount := GetEquipmentByLayer( me, 25 );
	if (!mount)
		OpenPaperdoll( me, me );
		return;
	endif`
Redundant.

**Comment by sigmantium** [comment]
`if ( serial == client->chr->serial )
  {
    ScriptDef sd;
    sd.quickconfig("scripts/misc/dblclickself.ecl");

    if (sd.exists())
    {
        ref_ptr<Bscript::EScriptProgram> prog;
        prog = find_script2(sd, false, Plib::systemstate.config.cache_interactive_scripts);
        if (prog.get() != NULL && client->chr->start_script(prog.get(), false))
        {
            return;
        }
    }
    else if ( paperdoll_macro_flag )
    {
        send_paperdoll(client, client->chr);
        return;     
    }
  }`
???

**Comment by frozenblit** [comment]
The paperdoll flag was used in the past only for macros (from the options menu), so that one could open their own paperdoll while mounted for example.

Newer clients use the paperdoll flag when double-clicking your own char, thus forcing the paperdoll to show up. I don't know what lead to this change (or when this happened).

Fixing this would require dropping support for the paperdoll macro by forcing the double-click script to run regardless of the macro flag. This would require changing the double-click script to receive the macro flag and could lead to breaking changes.

Our choice over discord was to update the docs, noting there that newer clients are forcing the paperdoll to show up when un-mounted. I don't imagine a great demand for changing the default behavior - we would have heard about this inconsistency before. Anyone that needs another behavior could implement a packethook on the 0x6 packet and deal with breaking the paperdoll macro themselves.
