### ISSUE TITLE
GetConfigString screws up values

### ISSUE THREAD

**Issue by murderinc** [polserver/polserver#522]
It case of value consists of digits it seems like trying to cast to int and then value is incorrect due to overflow. 
For example "1092039985441558558" becomes "-1262202850".

**Comment by KevinEady** [comment]
Hi @murderinc ,

So this was fixed in #525. This change makes the core correctly identify `1092039985441558558` is not a valid int32, so it will return it as a string. This should work for this specific use-case.

There was some discussion in the discord channel to completely remove the auto-conversion from `GetConfigString`, as it is little misleading that this module function is called GetConfig*String* but can return a numeric value. This can have unexpected consequences, for example a config property `07363422` will return a numeric `1959698`.

On that note, do you have a specific use-case for `GetConfigString` to _always_ return the exact string in the configuration file, completely skipping the auto-conversion?

If this fix is sufficient for you, please feel free to close the issue.

Thanks, Kevin

**Comment by KevinEady** [comment]
Closing as described above.
