### ISSUE TITLE
Float/Double issues

### ISSUE THREAD

**Issue by DavidJSGardner** [polserver/polserver#636]
So while working on class system stuff, I stumbled upon an issue with floats/doubles. I am simply adding 0.1 to a value and getting some weird outputs which can be an issue if I am doing comparisons.

Edit: Removed the print msg after the for loop...

```
use uo;
use os;
use math;

program test_follower_cap( mobile )

	var i:=0.0;
	for( i:=0.0; i<=5.0; i+=0.1 )
		Print( i );
		SleepMS( 100 );
	endfor
endprogram
```

The print out for the above code is as follows:
```
0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999
0.9999999999999999
1.0999999999999999
1.2
1.3
1.4000000000000001
1.5000000000000002
1.6000000000000003
1.7000000000000004
1.8000000000000005
1.9000000000000006
2.0000000000000004
2.1000000000000005
2.2000000000000006
2.3000000000000007
2.400000000000001
2.500000000000001
2.600000000000001
2.700000000000001
2.800000000000001
2.9000000000000012
3.0000000000000013
3.1000000000000014
3.2000000000000015
3.3000000000000016
3.4000000000000017
3.5000000000000018
3.600000000000002
3.700000000000002
3.800000000000002
3.900000000000002
4.000000000000002
4.100000000000001
4.200000000000001
4.300000000000001
4.4
4.5
4.6
4.699999999999999
4.799999999999999
4.899999999999999
4.999999999999998
```

**Comment by KevinEady** [comment]
Hi @DavidJSGardner ,

This is unfortunately a side-effect of how computers store floating-points in a `decimal` representation. For example, the following JavaScript snippet outputs the same values, because numbers in JavaScript are stored as a double-precision 64-bit binary format IEEE 754 value:

```js
for (var i = 0.0; i <= 5.0; i += 0.1) console.log(i)
```

```
0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6
0.7
0.7999999999999999
0.8999999999999999
0.9999999999999999
1.0999999999999999
1.2
1.3
...
4.4
4.5
4.6
4.699999999999999
4.799999999999999
4.899999999999999

```

You can read about it here at the aptly named website: https://0.30000000000000004.com/ 

One thing you can do is store the values in tenths and then display it to the user as `<value in tenths> / 10.0`:
```
for ( i:=0; i<=50; i+=1 ) Print( i/10.0 ); endfor
```
```
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1
1.1
1.2
1.3
...
4.5
4.6
4.7
4.8
4.9
5
```

**Comment by turleypol** [comment]
One additional note: the comparisons should work. For doubles the core does not assume that both sides are exactly equal. So 0.3000000001==0.3 is true
